### ISSUE TITLE
Experiments on CTB dataset

### ISSUE THREAD

**Issue by Caz-T** [thomaslu2000/Incremental-Parsing-Representations#1]
Hi, 
I read your paper and is particularly interested in applying your method and training models on CTB datasets. I noticed you provided a pipeline for CTB preprocessing, so i come to wonder whether you have conducted any experiments on Chinese datasets and summarized a set of hyperparameters that can produce nice results. If so, would it be possible to share such hyperparameters or even better, pretrained models, if that would be ok? 
I'd greatly appreciate your assistance.

**Comment by nikitakit** [comment]
Hi!

We unfortunately don't have any experiments on Chinese. The main constraint we were running up against is that an incremental parser should be using a unidirectional transformer like GPT-2, not a bidirectional transformer like BERT. Unfortunately GPT-2 is English-only and we're not quite sure what the closest equivalent is for Chinese. My past experience outside English has only been with bi-directional models.

The CTB processing scripts we have are all carried over from [benepar](https://github.com/nikitakit/self-attentive-parser), which does evaluate on CTB but is not incremental. I don't expect training this parser on Chinese to be particularly difficult, as long as you know of an appropriate pre-trained model to incorporate.

**Comment by Caz-T** [comment]
Ah I get that, thanks for the reply!
